### ISSUE TITLE
Translation Chapter One

### ISSUE THREAD

**Issue by JMEspiz** [AlexR1712/js-stack-from-scratch#1]
### Chapter: One

Hi everyone, I'm translating the chapter One. When I complete it, I'll send PR.

**Comment by JMEspiz** [comment]
Hi @AlexR1712. Two and half question xD:

1- are the comments always in English for Issues? or it's possible to write it in Spanish?.

2-I 've changed some part of the chapter one to improve the reading in the Spanish version. I'm going to send the PR. Could you review my translation?

**Comment by AlexR1712** [comment]
Hola @JMEspiz en cuanto a tus preguntas, vamos hacer algo ya que la idea de este repositorio es dar a conocer la información en español, es conveniente usar los comentarios en este idioma, no le veo inconveniente alguno, así también animamos a los lectores que si ven algún error, nos puedan apoyar.
1. Ya he revisado tu PR, te envie unas pequeñas correcciones del resto esta perfecto. Muchas gracias por tu tiempo.

Saludos! 👍
